; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[esp32s3]
framework = arduino
board = esp32-s3-devkitc-1
platform = espressif32@6.13.0
lib_deps = 
	h2zero/NimBLE-Arduino@^2.1.0
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.3
	rpolitex/ArduinoNvs@^2.10
	mikaeltulldahl/AsyncOta@^1.0.2
	https://github.com/s00500/ESPUI.git#master
	https://github.com/Ultrawipf/VescUart.git#master

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32s3_usb]
monitor_speed = 115200
board_upload.flash_size = 8MB

framework = ${esp32s3.framework}
platform = ${esp32s3.platform}
board = ${esp32s3.board}
build_flags = ${esp32s3.build_flags}
lib_deps = ${esp32s3.lib_deps}


[env:esp32s3_ota]
extra_scripts = platformio_upload.py
upload_protocol = custom
custom_ota_upload_url  = http://hypervcu.internal/upload
board_upload.flash_size = 8MB

framework = ${esp32s3.framework}
platform = ${esp32s3.platform}
board = ${esp32s3.board}
build_flags = ${esp32s3.build_flags}
lib_deps = ${esp32s3.lib_deps}

